/*        _         _             _       _                  _          _            _            _   _            _
*         /\ \      /\ \         /\ \     /\_\               / /\       /\ \         /\ \         /\_\/\_\ _      /\ \
*        /  \ \     \_\ \       /  \ \   / / /         _    / /  \      \_\ \       /  \ \       / / / / //\_\   /  \ \
*       / /\ \ \    /\__ \     / /\ \ \  \ \ \__      /\_\ / / /\ \__   /\__ \     / /\ \ \     /\ \/ \ \/ / /__/ /\ \ \
*      / / /\ \_\  / /_ \ \   / / /\ \ \  \ \___\    / / // / /\ \___\ / /_ \ \   / / /\ \ \   /  \____\__/ //___/ /\ \ \
*     / / /_/ / / / / /\ \ \ / / /  \ \_\  \__  /   / / / \ \ \ \/___// / /\ \ \ / / /  \ \_\ / /\/________/ \___\/ / / /
*    / / /__\/ / / / /  \/_// / /    \/_/  / / /   / / /   \ \ \     / / /  \/_// / /   / / // / /\/_// / /        / / /
*   / / /_____/ / / /      / / /          / / /   / / /_    \ \ \   / / /      / / /   / / // / /    / / /        / / /    _
*  / / /\ \ \  / / /      / / /________  / / /___/ / //_/\__/ / /  / / /      / / /___/ / // / /    / / /         \ \ \__/\_\
* / / /  \ \ \/_/ /      / / /_________\/ / /____\/ / \ \/___/ /  /_/ /      / / /____\/ / \/_/    / / /           \ \___\/ /
* \/_/    \_\/\_\/       \/____________/\/_________/   \_____\/   \_\/       \/_________/          \/_/             \/___/_/
*
*
* Main Project: PA Mischpult
* Based on ATxMega256A3U µController
*
* Module: dsp.h
* Maps register addresses of DSP as generated by Pure Path Studio
* Defines functions for DSP management
*
*/


#ifndef DSP_H_
#define DSP_H_


//Defines of PPS mapped registers

#define muxreg 0x23				//Input Multiplex
#define volreg 0x24				//Master Volume Regulator
#define vuenbl 0x42				//VU Meter Register
#define specenbl 0x47			//Spectrum Analyzer Register

//Function declarations
void switchdspinput(uint8_t int_channel, uint8_t ext_channel);
uint8_t readmastervolume(void);
void setmastervolume(uint8_t level);
void vumeter(unsigned char update_on);
void spectrum(unsigned char update_on);
void mute(unsigned char mute_on_off);
void volumeup(void);
void volumedown(void);


#endif /* DSP_H_ */